### ISSUE TITLE
Availability of GeodesicExact

### ISSUE THREAD

**Issue by mbotto123** [mrJean1/PyGeodesy#51]
I need to calculate geodesics on ellipsoids with high flattening, and from my understanding this is possible with the GeodesicExact class of GeographicLib. My problem is that this class isn't available in the Python version of GeographicLib, so a search for alternate options led me here. Is the GeodesicExact class available in PyGeodesy? I saw a reference to it in the PyGeodesy documentation for the elliptic module ("This provides the elliptic functions and integrals needed for Ellipsoid, GeodesicExact, and TransverseMercatorExact."). But I searched throughout the documentation and I couldn't find any other references to it. I apologize if I'm missing something obvious.

If it's not available here, I would appreciate any other suggestions for calculating geodesics on ellipsoids with high flattening using Python, since I'm having a lot of trouble with this.

**Comment by mrJean1** [comment]
Sorry, the `GeodesicExact` module from Karney's `GeographicLib` is not available in Python in `PyGeodesy`. 

However, there are Python versions of `TransverseMercatorExact` and `Elliptic` in `PyGeodesy` modules [etm](https://github.com/mrJean1/PyGeodesy/blob/master/pygeodesy/etm.py) and [elliptic](https://github.com/mrJean1/PyGeodesy/blob/master/pygeodesy/elliptic.py), respectively.  Those were added to `PyGeodesy` when several other `PyGeodesy` modules needed `Elliptic`.

Adding `GeodesicExact` would be possible, but tricky since it is unclear whether the required accuracy can be obtained with _plain_ Python (meaning without multi-precision floating point), e.g. to get the same or comparable test results.  The C++ code of `GeographicLib` can be compiled with different options for higher numerical accuracy and that may (or may not) be necessary for `GeodesicExact`.

One option may be to use the `GeographicLib` with a Python/Cython-to-C++ binding, like [this one (untested)](https://github.com/megaserg/geographiclib-cython-bindings).  Or, use that as an example to create a similar binding for the specific `GeodesicExact` functions needed.

If possible, please post one or a few examples of the high flattening case with expected results.

HTH
____
PS) The search results showed `GeodesicExact` and `TransverseMercatorExact` because some of the `GeographicLib` documentation is is copied in PyGeodesy.

**Comment by mrJean1** [comment]
FYI, a pure Python version of `GeodesicExact` and `GeodesicLineExact` is forthcoming, as a new module named `pygeodesy.geodesicx`.  Plus another new module `pygeodesy.geodsolve` invoking the `GeographicLib/GeodSolve` utility iff installed.  Testing is still ongoing.

**Comment by mbotto123** [comment]
Thank you very much for your thorough responses! I evaluated the options you originally suggested and it turned out that the `GeodSolve` utility was the most practical to implement in the limited time that I had, so that's what I ended up using. Unfortunately, I don't have access to expected results, so that's why I wasn't able to post that. It's good to hear that the classes have been added to `PyGeodesy` though.
