### ISSUE TITLE
"help wanted"  converting between ellipsoidal and orthometric to calculate height above ground

### ISSUE THREAD

**Issue by kerinb** [mrJean1/PyGeodesy#65]
Hello, 

Probably a basic question, but I'm struggling to wrap my head around a problem I am facing and spotting any potential errors in my thought process./work flow. 

I am recording latitude, longitude and altitude measurements from an android phone, and I am trying to get a relatively accurate measurement for my height above ground. 

Given that I have the ellipsoidal height from the [android api](https://developer.android.com/reference/android/location/Location#getAltitude()), how can I calculate the height above ground for the measurements I have taken? 

I have been trying to use this library for the above purpose. Using the EGM96 datum with geoids.GeoidKarney to get the geoid height for my coordinates. I have also been using the elevation data from ASTER to get the altitude of the earth/elevation at the given coordinates. 

So, if my understanding is correct, I should be able to calculate my height above ground by subtracting both the aster elevation and the geoid height from my altitude? However, when I try this, most of my altitudes are below ground? 

From my understanding, ASTER is measured against EGM96, and the android api is measured against WGS84. So, if my understanding is correct, my methodology should be sound? but I cant figure out why the altitudes are being 'classified' as being below ground/returning a negative height above ground for my tests that are above ground?

Any help and/or advice on this would be greatly appreciated, as I feel I have hit a dead end.

**Comment by mrJean1** [comment]
If ASTER is measured against the EGM96 geoid, then the ASTER heights are the same as those from `pygeodesy.GeoidKarney` instantiated with one of the `egm_pgm` files for the applicable lat-/longitude region.

According to the API, the Android heights are measured against WGS84, a smooth, ellipsoidal earth model which is quite different from geoids.  Therefore, subtracting the Android height from a EGM96 height, produces the difference between EGM96 and WGS84 at that lat-/longitude.  And that be negative or positive (or perhaps even zero in a few places), like the results you are seeing.

Since geoids are closer to the _actual earth surface_, the height from ASTER or `pygeodesy.GeoidKarney` is the more accurate height above ground at any lat-/longitude.  Same for other geoids.

Take the lat- and longitude from Android and pass those to an `pygeodesy.GeoidKarney` instance to get the height.  See the **Typical usage** [here](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.geoids-module.html).

HTH

**Comment by kerinb** [comment]
Hey @mrJean1 ,

Thank you for the response, I really appreciate it. 

I am still a little confused if I'm honest. The ASTER data is a digital elevation model (measured against EGM96), while I thought `pygeodesy.GeoidKarney` was  the geoid height; i.e. the difference between the ellipsoid and geoid at a given lat/long? In which, to convert the ASTER elevation from orthometric to ellipsoidal I have to add the results from `pygeodesy.GeoidKarney` to the aster elevation results? As seen [here](http://www.geomobileinnovations.com/images/131.jpg) 

When I use only the `pygeodesy.GeoidKarney` with the Android altitude, pretty much all of my results are positive, but higher than expected; 10 to 30 meters above ground while I'm walking down the street. I will try the egm08 file and see if that makes much of a difference, and test my device to make sure its configured correctly and go from there. 

If all that I need to do is subtract the `pygeodesy.GeoidKarney` results from the Android altitude, that sure would simplify my process and make things a lot easier. 

If you could confirm what exactly `pygeodesy.GeoidKarney` is returning I would greatly appreciate it, as I think my understanding of all of this may be a bit off?

Thanks again and I really appreciate the help,
Breandán

**Comment by mrJean1** [comment]
The [pygeodesy.GeoidKarney](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.geoids.GeoidKarney-class.html) interpolator produces the [geoid height N](http://www.geomobileinnovations.com/images/131.jpg) by Karney's interpolation.  Use the [egm2008-1](https://geographiclib.sourceforge.io/html/geoid.html#geoidinst) or `egm2008-2_5` data set for the most accurate results for **N**.

Or use the [pygeodesy.GeoidPGM](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.geoids.GeoidPGM-class.html) class with one of the same `egm` data sets and choose one of several other interpolation methods.  Note, `pygeodesy.GeoidPGM` requires a recent release of [scipy](https://pypi.org/project/scipy/) to be installed.

The ellipsoidal height **h** reported by Android is _GPS-based_ and may be off by several 10s of meters, see for example [here](https://support.memory-map.com/862250-The-GPS-Altitude-on-my-Android-device-is-off-by-50m) and [here](https://stackoverflow.com/questions/9361870/android-how-to-get-accurate-altitude).  The discrepancies of 10 to 30 meters may just be due to that.

Lastly, function [pygeodesy.geoidHeight2](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.elevations-module.html#geoidHeight2) returns the ellipsoidal height **h** for a lat-/longitude using the NOAA/NGS web service.  However, that height **h** is relative to the NAD83/NADV88 ellipsoid and must be adjusted for other ellipsoids.  Use method [LatLon.geoidHeight2](https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.ellipsoidalBase.LatLonEllipsoidalBase-class.html#geoidHeight2) from any of the `pygeodesy.ellipsoidal...` modules to get the **h** adjusted for the datum used.

**Comment by kerinb** [comment]
Thank you very much for all the detail. I really appreciate the help. I reckon the difference must be from the GPS data, I will see if there is anything else I can do, but im doubtful after seeing this. 
Thanks again :)

**Comment by mrJean1** [comment]
There are other Android (and iPhone) apps claiming to offer better, more accurate altitudes.  But it is unclear how that is accomplished with the standard API.  Perhaps with some other API or some external device like an altimeter, not sure.
